server:
  port: 8083
eureka:
  client:
    service-url:
      defaultZone: http://registry-service:8761/eureka/
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          routes:
            - id: ms-productos
              uri: http://ms-productos:8081
              predicates:
                - Path=/products/**
  security:
    oauth2:
      client:
        registration:
          oauth-client:
            provider: oauth-server
            client-id: oauth-client
            client-secret: 12345678910
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8083/authorized            
            scope: openid,profile
        provider:
          oauth-server:
            authorization-uri: http://localhost:9000/oauth2/authorize
            token-uri: http://localhost:9000/oauth2/token
            user-info-uri: http://localhost:9000/userinfo
            user-name-attribute: sub
            jwk-set-uri: http://localhost:9000/oauth2/jwks
