server:
  port: 8081
spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/db_productos_dev
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin}
logging:
  level:
    root: INFO
    org.springframework.r2dbc: DEBUG
    
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  security:
    enabled: false