spring:
  application:
    name: ms-pedidos
  r2dbc:
    url: r2dbc:postgresql://db:5432/syncap
    username: postgres
    password: admin
  main:
    web-application-type: reactive
server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://registry-service:8761/eureka/
