server:
  port: 8082
spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/db_pedidos_qa}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: update
ms-productos:
  url: ${MS_PRODUCTOS_URL:http://localhost:8081}
