server:
  port: 8082
spring:
  application:
    name: ms-pedidos
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/db_pedidos_qa
    username: postgres
    password: admin
  main:
    web-application-type: reactive
ms-productos:
  url: http://localhost:8081
