server:
  port: 8081
spring:
  application:
    name: ms-productos
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/db_productos_qa
    username: postgres
    password: admin
  main:
    web-application-type: reactive
