server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_productos_qa
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    root: INFO
