server:
  port: 8082
spring:
  r2dbc:  # Cambiar de datasource a r2dbc
    url: ${DB_URL:r2dbc:postgresql://localhost:5432/db_pedidos_dev}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin}
ms-productos:
  url: ${MS_PRODUCTOS_URL:http://localhost:8081}

logging:
  level:
    root: INFO