server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_productos_prd
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
logging:
  level:
    root: WARN
